# Generated by Django 5.0.7 on 2024-07-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_musicpost_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_file', models.FileField(upload_to='music/')),
            ],
        ),
        migrations.RemoveField(
            model_name='musicpost',
            name='music_file',
        ),
        migrations.AddField(
            model_name='musicpost',
            name='music_path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.musicpath'),
        ),
    ]
